"""Keyword-based topic labelling for news items."""

from __future__ import annotations

# Label -> list of keywords (lowercase); match if any keyword appears in title or description
LABEL_KEYWORDS: dict[str, list[str]] = {
    "financial": [
        "stock",
        "market",
        "trading",
        "invest",
        "bank",
        "economy",
        "recession",
        "inflation",
        "fed",
        "interest rate",
        "earnings",
        "revenue",
        "profit",
        "dollar",
        "yuan",
        "bitcoin",
        "crypto",
        "wall street",
        "nasdaq",
        "s&p",
        "gdp",
        "unemployment",
        "central bank",
        "treasury",
        "bond",
        "ipo",
        "merger",
        "acquisition",
        "dividend",
        "forex",
        "commodity",
        "oil price",
    ],
    "sports": [
        "football",
        "soccer",
        "basketball",
        "baseball",
        "tennis",
        "olympics",
        "world cup",
        "championship",
        "nba",
        "nfl",
        "mlb",
        "premier league",
        "match",
        "game",
        "score",
        "player",
        "team",
        "league",
        "tournament",
        "goal",
        "touchdown",
        "home run",
        "medal",
        "athlete",
        "coach",
    ],
    "politics": [
        "election",
        "president",
        "congress",
        "senate",
        "parliament",
        "vote",
        "democrat",
        "republican",
        "government",
        "minister",
        "law",
        "bill",
        "policy",
        "sanction",
        "diplomat",
        "summit",
        "nato",
        "un ",
        "united nations",
        "protest",
        "rally",
        "campaign",
        "impeach",
        "cabinet",
        "legislation",
    ],
    "game": [
        "video game",
        "gaming",
        "esports",
        "playstation",
        "xbox",
        "nintendo",
        "steam",
        "twitch",
        "streamer",
        "gamer",
        "game release",
        "dlc",
        "league of legends",
        "fortnite",
        "minecraft",
        "valorant",
        "overwatch",
    ],
    "entertainment": [
        "movie",
        "film",
        "celebrity",
        "actor",
        "actress",
        "oscar",
        "grammy",
        "netflix",
        "disney",
        "marvel",
        "star wars",
        "box office",
        "premiere",
        "album",
        "music",
        "concert",
        "tour",
        "broadway",
        "tv show",
        "series",
    ],
    "technology": [
        "apple",
        "google",
        "microsoft",
        "amazon",
        "meta",
        "facebook",
        "ai",
        "artificial intelligence",
        "software",
        "hardware",
        "chip",
        "semiconductor",
        "iphone",
        "android",
        "startup",
        "tech",
        "internet",
        "cyber",
        "hack",
        "robot",
        "electric vehicle",
        "ev ",
        "tesla",
        "spacex",
        "5g",
    ],
    "science": [
        "research",
        "study",
        "scientist",
        "nasa",
        "space",
        "climate",
        "planet",
        "vaccine",
        "discovery",
        "experiment",
        "journal",
        "paper",
        "university",
    ],
    "health": [
        "covid",
        "virus",
        "pandemic",
        "hospital",
        "doctor",
        "medical",
        "health",
        "disease",
        "treatment",
        "drug",
        "fda",
        "vaccine",
        "patient",
        "outbreak",
    ],
}


def label_item(title: str, description: str | None = None) -> list[str]:
    """Assign topic labels from title and optional description using keyword match.

    Returns a list of label strings (e.g. ['financial', 'politics']).
    """
    text = (title or "") + " " + (description or "")
    text_lower = text.lower().strip()
    if not text_lower:
        return []

    labels: list[str] = []
    for label, keywords in LABEL_KEYWORDS.items():
        for kw in keywords:
            if kw in text_lower:
                labels.append(label)
                break
    return labels
